export const districtToTowns = {
    "Colombo": ["Dehiwala", "Moratuwa", "Kaduwela", "Homagama", "Kolonnawa", "Kesbewa", "Maharagama", "Sri Jayawardenepura Kotte"],
    "Gampaha": ["Negombo", "Wattala", "Kelaniya", "Gampaha", "Minuwangoda", "Kadawatha", "Ja-Ela"],
    "Kalutara": ["Panadura", "Horana", "Kalutara", "Bandaragama", "Beruwala", "Mathugama"],
    "Kandy": ["Kandy", "Gampola", "Nawalapitiya", "Peradeniya", "Katugastota", "Pilimatalawa"],
    "Matale": ["Matale", "Dambulla", "Galewela", "Ukuwela", "Rattota", "Yatawatta"],
    "Nuwara Eliya": ["Nuwara Eliya", "Hatton", "Talawakele", "Maskeliya", "Kotagala"],
    "Galle": ["Galle", "Ambalangoda", "Hikkaduwa", "Baddegama", "Elpitiya"],
    "Matara": ["Matara", "Weligama", "Akuressa", "Dickwella", "Hakmana"],
    "Hambantota": ["Hambantota", "Tangalle", "Beliatta", "Ambalantota", "Tissamaharama"],
    "Jaffna": ["Jaffna", "Nallur", "Chavakachcheri", "Point Pedro", "Chankanai"],
    "Kilinochchi": ["Kilinochchi", "Pallai", "Kandavalai", "Poonakary"],
    "Mannar": ["Mannar", "Madhu", "Nanattan", "Musali"],
    "Vavuniya": ["Vavuniya", "Cheddikulam", "Nedunkeni"],
    "Mullaitivu": ["Mullaitivu", "Oddusuddan", "Puthukkudiyiruppu"],
    "Batticaloa": ["Batticaloa", "Kattankudy", "Eravur", "Valaichchenai"],
    "Ampara": ["Ampara", "Kalmunai", "Sammanthurai", "Akkaraipattu"],
    "Trincomalee": ["Trincomalee", "Kantale", "Kinniya", "Muttur"],
    "Kurunegala": ["Kurunegala", "Kuliyapitiya", "Polgahawela", "Narammala"],
    "Puttalam": ["Puttalam", "Chilaw", "Wennappuwa", "Nattandiya"],
    "Anuradhapura": ["Anuradhapura", "Kekirawa", "Medawachchiya", "Tambuttegama"],
    "Polonnaruwa": ["Polonnaruwa", "Kaduruwela", "Hingurakgoda", "Medirigiriya"],
    "Badulla": ["Badulla", "Bandarawela", "Welimada", "Haputale"],
    "Monaragala": ["Monaragala", "Wellawaya", "Bibile", "Buttala"],
    "Ratnapura": ["Ratnapura", "Embilipitiya", "Balangoda", "Pelmadulla"],
    "Kegalle": ["Kegalle", "Mawanella", "Warakapola", "Dehiowita"]
};